name: GitHub Actions Eslint

on: 
  push:
    branches: [main]

jobs:
  Explore-GitHub-Actions:
    defaults:
      run:
        working-directory: ./front
    runs-on: ubuntu-latest
    steps:
      - run: npm install
      - run: eslint ./*
