name: GitHub Actions Eslint

on: 
  push:
    branches: [main]

jobs:
  Explore-GitHub-Actions:
    defaults:
      run:
        working-directory: ./front
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: eslint ./*
